name: get-ip
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '0 */24 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.12'
      - run: pip install requests
      - run: python ./ipchange.py
      - name: Commit and push changes
        run: |
          git config --global user.name ${{ secrets.EMAIL }}
          git config --global user.email ${{ secrets.NAME }}
          git add .
          git commit -m "Update files"
          git push
